configuration: 
  name: oaqa-tutorial
  author: oaqa


collection-reader:
  inherit: collection_reader.fs-collection-reader
  file: /data/WatsonConferenceRooms.txt
pipeline:
  - inherit: ecd.phase  
    name: RoomNumberAnnotator
    options: |
      - inherit: tutorial.ex2.RoomNumberAnnotator
  - inherit: cas_consumer.XmiWriterCasConsumer